doc-valid-idents = [
    "MaxNovo",
    "MaxQuant",
    "..",
    "GNOme",
    "ProForma",
    "OPair",
    "MSFragger",
    "MZTab",
    "PSM_ID",
    "DeepNovo",
    "PGPointNovo",
    "PointNovo",
    "BiatNovo",
    "InstaNovo",
    "DeepNovoFamily",
    "PointNovoFamily",
    "PowerNovo",
    "PepNet",
    "pi-PrimeNovo",
    "Ï€-PrimeNovo",
]
avoid-breaking-exported-api = false
check-private-items = true
