[package]
name = "rustyms-py"
version = "0.8.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustyms_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
rustyms = { path = "../rustyms" }
ordered-float = { version = "4.2", features = ["serde"] }
